name: arpa_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.*
  - dask=2023.1.*
  - geopandas=0.12.*
  - pip=22.3.*
  - matplotlib=3.6.*
  - ipywidgets=7.*
  - seaborn=0.*
  - pip:
    - sodapy==2.2.0